version: '3.4'

services:
  expdocker:
    image: expdocker
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:8080
