# name: Deploy To Cloud

# on:
#   push:
#     branches:
#       - main

# env:
#   CI: true
#   CARGO_TERM_COLOR: always

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     environment: PROD
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Google Cloud Auth
#         uses: google-github-actions/auth@v2
#         with:
#           credentials_json: "${{ secrets.GCP_SA_KEY }}"

#       - name: Set up Cloud SDK
#         uses: "google-github-actions/setup-gcloud@v2"

#       - name: Configure Docker
#         run: |
#           gcloud auth configure-docker ${{ secrets.GCP_LOCATION}}-docker.pkg.dev --quiet

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Build and Push Docker Image
#         uses: docker/build-push-action@v6
#         with:
#           context: .
#           push: true
#           tags: ${{ secrets.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/react-vite-web/web:latest
#           cache-from: type=gha
#           cache-to: type=gha,mode=max

#       - uses: 'google-github-actions/deploy-cloudrun@v2'
#         with:
#           region: ${{ secrets.GCP_LOCATION }}
#           image: ${{ secrets.GCP_LOCATION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/react-vite-web/web:latest
#           service: ${{ secrets.GCR_SERVICE_NAME}}